sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - bower_components
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

script:
  - gulp lint
  - travis_retry xvfb-run wct
  - travis_retry xvfb-run wct --dom=shadow
