sudo: false
dist: trusty
language: node_js
node_js: 8.0

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - bower install

before_script:
  - npm run lint
  - xvfb-run -s '-screen 0 1024x768x24' polymer test

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      npm i --no-save gemini@^4.0.0 gemini-sauce gemini-polyserve &&
      gemini test test/visual &&
      gemini test test/visual -c .gemini-chrome.yml &&
      wct --env saucelabs;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      wct --env saucelabs-cron;
    fi
